version: '3.4'

services:
  pollposition.api:
    image: pollposition.api
    ports:
      - "5209:80"
    environment:
      GoogleKey: ${GOOGLE_KEY}
      RedisConnectionString: ${REDIS_CONNECTION_STRING}
    build:
      context: .
      dockerfile: Api/Dockerfile
    depends_on:
      - redis

  pollposition.integrationtests:
    image: pollposition.integrationtests
    build: 
      context: .
      dockerfile: Tests/Dockerfile
    environment:
      API_URL: http://pollposition.api
      GoogleKey: ${GOOGLE_KEY}
      RedisConnectionString: ${REDIS_CONNECTION_STRING}
    entrypoint: dotnet test
    depends_on:
      - pollposition.api

  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:  
  redis_data: