version: '3.4'

services:
  api:
    image: pollposition

  integration:
    entrypoint: dotnet test --logger trx --results-directory /app/Tests/testresults
    volumes:
      - ${TEST_RESULT_PATH}:/app/Tests/testresults
