version: '3.4'

services:
  pollposition.api:
    image: pollposition.api

  pollposition.integrationtests:
    entrypoint: dotnet test --logger trx --results-directory /app/Tests/testresults
    volumes:
      - C:\Final\PollPosition\Tests\results:/app/Tests/testresults
